default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

dev_default: &dev_default
  <<: *default
  host: localhost
  user: <%= ENV['DEV_DB_USER'] %>
  password: <%= ENV['DEV_DB_PASS'] %>

development:
  <<: *dev_default
  database: scheduler_development

test: &test
  <<: *dev_default
  database: scheduler_test

production:
  <<: *default
  database: <%= ENV['DB_NAME'] %>
  host: <%= ENV['DB_HOST'] %>
  port: <%= ENV['DB_PORT'] %>
  user: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASS'] %>
